name: static_resources_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  # Включаем Material Icons
  uses-material-design: true

  # Подключаем изображения
  assets:
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg

  # Подключаем пользовательский шрифт
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
